services:
  db:
    image: postgres:15-alpine
    container_name: contact_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: contact
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: contact_backend
    restart: always
    # The 'command' below is the magic part for Sequelize
    command: >
      sh -c "npx sequelize-cli db:migrate && node index.js"
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASS='1234'
      - DB_NAME=contact
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: contact_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: